TRUNCATE TABLE demo_db.PUBLIC.HR_EMP_DATA;

COPY INTO demo_db.PUBLIC.HR_EMP_DATA
FROM @demo_db.public.my_stage_int2
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  ESCAPE = NONE
  ESCAPE_UNENCLOSED_FIELD = NONE
)
ON_ERROR = 'CONTINUE';

Truncate table demo_db.PUBLIC.HR_EMP_DATA;
--FORCE = TRUE;

Select count(*) AS CNT_BEFORE FROM demo_db.PUBLIC.HR_EMP_DATA;

SELECT COUNT(*) AS CNT_AFTER FROM demo_db.PUBLIC.HR_EMP_DATA;
