COPY INTO demo_db.PUBLIC.HR_EMP_DATA
FROM @demo_db.public.my_stage_int2
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
  --ESCAPE = NONE
  --ESCAPE_UNENCLOSED_FIELD = NONE
)
VALIDATION_MODE = 'RETURN_ERRORS';
